spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        default_schema: COFFEE_SHOP
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dev
    username: user
    password: password
  liquibase:
    change-log: classpath*:db/changelog/db.changelog-master.yaml
    enabled: true
logging:
  level:
    liquibase: DEBUG
    org:
      springframework:
        web: DEBUG
jwt:
  secret: secretJwT12223*
password:
  salt: 12309876