spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        default_schema: COFFEE_SHOP
  datasource:
    url: jdbc:h2:mem:myDb;INIT=create domain if not exists jsonb as text;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
  liquibase:
    change-log: classpath*:db/changelog/db.changelog-master.yaml
    enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  level:
    liquibase: INFO
    org:
      springframework:
        web: DEBUG
jwt:
  secret: secretJwT12223*
password:
  salt: 12309876